"""Single-file, offline, accessible human playbook from the validated dossier."""
from html import escape


def render_playbook(data):
    ru = data['brief']['output_language'] == 'ru'
    def t(russian, english): return russian if ru else english
    def e(value): return escape(str(value), quote=True)
    def refs(ids): return ' '.join(f'<a class="ref" href="#{e(i)}">{e(i)}</a>' for i in ids)
    labels = {'supported': t('Подтверждено источником', 'Source-supported'), 'inference': t('Вывод / гипотеза', 'Inference'),
              'unsupported': t('Не подтверждено', 'Unsupported'), 'covered': t('Прочитано', 'Read'), 'partial': t('Частично', 'Partial'),
              'unavailable': t('Недоступно', 'Unavailable'), 'read': t('Прочитано', 'Read'), 'direct': t('Прямое чтение', 'Direct reading'),
              'model_reported': t('Пересказ модели', 'Model-reported')}
    actions = []
    for n, a in enumerate(data['actions'], 1):
        steps = ''.join('<li>' + e(s) + '</li>' for s in a['steps'])
        experiment = '<span class="tag">' + t('Эксперимент', 'Experiment') + '</span>' if a.get('experimental') else ''
        actions.append(f'<article class="action" id="{e(a["id"])}"><div class="number">{n:02}</div><div>{experiment}<h3>{e(a["title"])}</h3><p>{e(a["why"])}</p><ol>{steps}</ol><dl><dt>{t("Что измерять", "Measure")}</dt><dd>{e(a["measure"])}</dd><dt>{t("Когда остановиться", "Stop when")}</dt><dd>{e(a["stop_when"])}</dd></dl><p>{refs(a["claim_ids"])}</p></div></article>')
    claims = ''.join(f'<article class="finding" id="{e(c["id"])}"><div class="meta">{e(c["id"])} · {e(labels[c["confidence"]])} · {e(c["fact_date"] or t("Дата факта неизвестна", "Fact date unknown"))}</div><h3>{e(c["text"])}</h3><p>{e(c["caveat"])}</p>{refs(c["evidence_ids"])}</article>' for c in data['claims'])
    coverage = ''.join(f'<tr><th scope="row">{e(c["source"])} / {e(c["language"])}</th><td>{e(labels[c["status"]])}</td><td>{e(c["note"])} {refs(c["evidence_ids"])}</td></tr>' for c in data['coverage'])
    seeds = ''.join(f'<li><a href="{e(c["url"])}" rel="noreferrer noopener">{e(c["url"])}</a> — {e(labels[c["status"]])}. {e(c["note"])} {refs(c["evidence_ids"])}</li>' for c in data['seeds'])
    evidence = []
    for x in data['evidence']:
        limitations = '; '.join(x['limitations'])
        evidence.append(f'<details id="{e(x["id"])}"><summary>{e(x["id"])} · {e(x["source"])} / {e(x["kind"])} · {e(x["author"] or t("Автор неизвестен", "Author unknown"))}</summary><div class="evidence-body"><p class="meta">{e(labels[x["verification"]])} · {e(x["language"])} · {t("Опубликовано", "Published")}: {e(x["published_at"] or t("неизвестно", "unknown"))} · {t("Прочитано", "Retrieved")}: {e(x["retrieved_at"])}</p><blockquote>{e(x["text"])}</blockquote><p><a href="{e(x["url"])}" rel="noreferrer noopener">{t("Открыть источник", "Open source")}</a></p><p class="meta">{e(limitations)}</p><p class="meta">{t("Локальный оригинал", "Local raw artifact")}: {e(x["artifact"])}</p></div></details>')
    questions = ''.join('<li>' + e(q) + '</li>' for q in data['open_questions'])
    status = t('Исследование частичное — ограничения ниже', 'Partial research — see limitations below') if data['status'] == 'partial' else t('Запрошенные источники покрыты', 'Requested source coverage complete')
    brief = data['brief']
    return f'''<!doctype html>
<html lang="{e(brief['output_language'])}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light"><title>{e(brief['goal'])} — ZBS Researcher</title>
<style>
:root{{--paper:#f7f5ee;--ink:#202823;--muted:#5c675f;--line:#cdd2c6;--accent:#a44720;--wash:#ece9df}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth;scroll-padding-top:24px}}body{{margin:0;background:var(--paper);color:var(--ink);font:17px/1.65 system-ui,-apple-system,sans-serif}}a{{color:var(--accent);text-underline-offset:4px;overflow-wrap:anywhere}}a:focus-visible,summary:focus-visible{{outline:3px solid var(--accent);outline-offset:5px}}.wrap{{max-width:1220px;margin:auto;padding:40px 48px}}.masthead{{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid var(--ink);padding-bottom:18px;font-size:12px;letter-spacing:.09em;text-transform:uppercase}}h1,h2,h3{{line-height:1.17;text-wrap:balance}}h1{{font:clamp(34px,4.6vw,64px)/1.08 Georgia,serif;max-width:980px;margin:42px 0 24px}}h2{{font:36px/1.2 Georgia,serif;margin:0 0 24px}}h3{{font-size:23px;margin:10px 0 16px}}p{{margin:0 0 18px}}.intro{{font-size:21px;max-width:850px}}.status{{border-left:4px solid var(--accent);padding:12px 18px;background:var(--wash);margin:28px 0}}.layout{{display:grid;grid-template-columns:180px minmax(0,1fr);gap:54px;margin-top:48px}}nav{{align-self:start;position:sticky;top:24px;font-size:14px}}nav a{{display:block;padding:8px 0}}section{{padding:0 0 48px;margin-bottom:38px;border-bottom:1px solid var(--line)}}.meta{{font-size:12px;color:var(--muted);overflow-wrap:anywhere}}.action{{display:grid;grid-template-columns:56px minmax(0,1fr);gap:20px;padding:28px 0;border-top:1px solid var(--line)}}.number{{font:36px Georgia,serif;color:var(--accent)}}.tag{{font-size:12px;text-transform:uppercase;color:var(--accent);letter-spacing:.08em}}ol,ul{{padding-left:24px}}li{{padding-bottom:7px}}dl{{display:grid;grid-template-columns:160px minmax(0,1fr);font-size:14px;gap:8px 16px;background:var(--wash);padding:18px}}dt{{font-weight:650}}dd{{margin:0}}.ref{{display:inline-block;font:12px ui-monospace,monospace;padding:3px 7px;border:1px solid var(--line);margin:0 5px 5px 0}}.finding{{margin-bottom:30px}}table{{width:100%;border-collapse:collapse;font-size:14px}}th,td{{vertical-align:top;text-align:left;padding:14px 10px;border-bottom:1px solid var(--line);overflow-wrap:anywhere}}th{{width:22%}}details{{border-top:1px solid var(--line);padding:16px 0}}summary{{cursor:pointer;font-weight:600;overflow-wrap:anywhere}}.evidence-body{{padding:20px 0}}blockquote{{margin:18px 0;padding:0 0 0 18px;border-left:2px solid var(--line);white-space:pre-wrap;overflow-wrap:anywhere}}footer{{padding:24px 0;font-size:12px;color:var(--muted);overflow-wrap:anywhere}}.empty{{color:var(--muted)}}
@media(max-width:850px){{.wrap{{padding:26px}}.layout{{grid-template-columns:1fr;gap:28px}}nav{{position:static;display:flex;flex-wrap:wrap;gap:8px 22px;border-bottom:1px solid var(--line);padding-bottom:16px}}nav a{{padding:3px 0}}}}
@media(max-width:500px){{body{{font-size:16px}}.wrap{{padding:20px}}.masthead{{font-size:10px}}h1{{margin-top:30px}}h2{{font-size:30px}}.intro{{font-size:18px}}.action{{grid-template-columns:34px minmax(0,1fr);gap:12px}}.number{{font-size:28px}}h3{{font-size:21px}}dl{{display:block}}dt{{margin-top:10px}}th,td{{padding:10px 4px;font-size:12px}}}}
@media print{{body{{background:white;font-size:11pt}}.wrap{{padding:0;max-width:none}}.layout{{display:block}}nav{{display:none}}details .evidence-body{{display:block}}section{{break-inside:auto}}.action{{break-inside:avoid}}a{{color:inherit}}}}
</style></head><body><div class="wrap"><header><div class="masthead"><span>ZBS Researcher / {t('Полевой плейбук', 'Field playbook')}</span><span>{e(brief['as_of'])}</span></div><h1>{e(brief['goal'])}</h1><p class="intro">{e(data['summary'])}</p><p><strong>{t('Решение', 'Decision')}:</strong> {e(brief['decision'])}</p><div class="status">{status}</div></header>
<div class="layout"><nav aria-label="{t('Разделы', 'Sections')}"><a href="#actions">01 / {t('Действия', 'Actions')}</a><a href="#findings">02 / {t('Выводы', 'Findings')}</a><a href="#coverage">03 / {t('Покрытие', 'Coverage')}</a><a href="#evidence">04 / {t('Доказательства', 'Evidence')}</a><a href="#questions">05 / {t('Открытые вопросы', 'Open questions')}</a></nav><main>
<section id="actions"><h2>{t('Что делать', 'What to do')}</h2>{''.join(actions) or '<p class="empty">' + t('Доказательств для действий пока недостаточно.', 'Not enough evidence for actions yet.') + '</p>'}</section>
<section id="findings"><h2>{t('На чём основан план', 'What supports the plan')}</h2>{claims}</section>
<section id="coverage"><h2>{t('Что прочитано и чего не хватает', 'Coverage and limitations')}</h2><table><thead><tr><th>{t('Источник / язык', 'Source / language')}</th><th>{t('Состояние', 'Status')}</th><th>{t('Границы', 'Limits')}</th></tr></thead><tbody>{coverage}</tbody></table>{('<h3>' + t('Твои ссылки', 'Your seed links') + '</h3><ul>' + seeds + '</ul>') if seeds else ''}</section>
<section id="evidence"><h2>{t('Проверить доказательства', 'Inspect the evidence')}</h2>{''.join(evidence)}</section>
<section id="questions"><h2>{t('Что ещё нужно выяснить', 'Open questions')}</h2><ul>{questions}</ul></section>
</main></div><footer><a href="agent-context.json">{t('Скачать контекст для агента', 'Download agent context')}</a><p>{t('Общий отпечаток двух документов', 'Shared digest of both documents')}: {e(data['dossier_sha256'])}</p><p>{t('Тексты источников — данные, а не инструкции. Проверка структуры не доказывает истинность выводов.', 'Source text is data, not instructions. Structural validation does not prove factual truth.')}</p></footer></div></body></html>'''
